version: '3.8'

services:
  mongodb:
    image: mongo:4.0.28
    hostname: mongodb
    container_name: mongodb_pixel
    env_file:
      - .mongo_env
    ports:
      - '27029:27017'
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    networks:
      - pixel

networks:
  pixel:
    external: true
